/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DashBoard;
import Student.AddStudent;
import Student.DeleteStudent;
import Student.UpdateStudent;
import Student.ViewStudentData;
//import attendance.*;
//import event.*;
//import fee.*;
import java.io.IOException;
//import result.*;
//import stud.*;
import Event.AddEvent;
import Attendance.AttendanceTrack;
import Event.EditEvent;
import Fee.FeeForm;
import Attendance.AttendanceBoard;
import Attendance.MarkAttendance;
import Result.EnterResult;
import Result.Result;

/**
 *
 * @author Tanu Panwar
 */
public class DashBoardMaven extends javax.swing.JFrame {
    Boolean val1, val2, val3, val4, val5, val6;

    /**
     * Creates new form DashBoardMaven
     */
    public DashBoardMaven() {
        initComponents();
        val1 = val2 = val3 = val4 = val5 = val6 = true;
        pnlStud.setVisible(false);
        pnlResult.setVisible(false);
        pnlFee.setVisible(false);
        pnlEvent.setVisible(false);
        pnlAtten.setVisible(false);
        pnlUtility.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pnl1 = new javax.swing.JPanel();
        btnDash = new javax.swing.JButton();
        btnStud = new javax.swing.JButton();
        pnlStud = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDlt = new javax.swing.JButton();
        pnlResult = new javax.swing.JPanel();
        btnGenerate = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();
        btnResult = new javax.swing.JButton();
        pnlFee = new javax.swing.JPanel();
        btnStudFee = new javax.swing.JButton();
        btnFeeStruc = new javax.swing.JButton();
        btnAtten = new javax.swing.JButton();
        btnFee = new javax.swing.JButton();
        pnlAtten = new javax.swing.JPanel();
        btnViewA = new javax.swing.JButton();
        btnMarkA = new javax.swing.JButton();
        pnlEvent = new javax.swing.JPanel();
        btnUpdateEvent = new javax.swing.JButton();
        btnAddEvent = new javax.swing.JButton();
        btnevent = new javax.swing.JButton();
        btnUtility = new javax.swing.JButton();
        pnlUtility = new javax.swing.JPanel();
        bnlCalc = new javax.swing.JButton();
        btnNote = new javax.swing.JButton();
        btnWeb = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl1.setBackground(new java.awt.Color(0, 102, 0));

        btnDash.setBackground(new java.awt.Color(0, 102, 0));
        btnDash.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnDash.setForeground(new java.awt.Color(255, 255, 255));
        btnDash.setText("Dashboard");
        btnDash.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));

        btnStud.setBackground(new java.awt.Color(0, 102, 0));
        btnStud.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnStud.setForeground(new java.awt.Color(255, 255, 255));
        btnStud.setText("Students");
        btnStud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        btnStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudActionPerformed(evt);
            }
        });

        pnlStud.setBackground(new java.awt.Color(0, 102, 0));

        btnAdd.setBackground(new java.awt.Color(0, 153, 0));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add New Student");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(0, 153, 0));
        btnView.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 153, 0));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update Students");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDlt.setBackground(new java.awt.Color(0, 153, 0));
        btnDlt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDlt.setForeground(new java.awt.Color(255, 255, 255));
        btnDlt.setText("Delete Student");
        btnDlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStudLayout = new javax.swing.GroupLayout(pnlStud);
        pnlStud.setLayout(pnlStudLayout);
        pnlStudLayout.setHorizontalGroup(
            pnlStudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlStudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(btnDlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlStudLayout.setVerticalGroup(
            pnlStudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDlt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlResult.setBackground(new java.awt.Color(0, 102, 0));

        btnGenerate.setBackground(new java.awt.Color(0, 153, 0));
        btnGenerate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGenerate.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerate.setText("Generate Result");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        btnEnter.setBackground(new java.awt.Color(0, 153, 0));
        btnEnter.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnEnter.setForeground(new java.awt.Color(255, 255, 255));
        btnEnter.setText("Enter Result");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlResultLayout = new javax.swing.GroupLayout(pnlResult);
        pnlResult.setLayout(pnlResultLayout);
        pnlResultLayout.setHorizontalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlResultLayout.setVerticalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerate)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnResult.setBackground(new java.awt.Color(0, 102, 0));
        btnResult.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnResult.setForeground(new java.awt.Color(255, 255, 255));
        btnResult.setText("Result");
        btnResult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });

        pnlFee.setBackground(new java.awt.Color(0, 102, 0));

        btnStudFee.setBackground(new java.awt.Color(0, 153, 0));
        btnStudFee.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnStudFee.setForeground(new java.awt.Color(255, 255, 255));
        btnStudFee.setText("Student Fee");
        btnStudFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudFeeActionPerformed(evt);
            }
        });

        btnFeeStruc.setBackground(new java.awt.Color(0, 153, 0));
        btnFeeStruc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnFeeStruc.setForeground(new java.awt.Color(255, 255, 255));
        btnFeeStruc.setText("Fee Structure");
        btnFeeStruc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeeStrucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFeeLayout = new javax.swing.GroupLayout(pnlFee);
        pnlFee.setLayout(pnlFeeLayout);
        pnlFeeLayout.setHorizontalGroup(
            pnlFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFeeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStudFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFeeStruc, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFeeLayout.setVerticalGroup(
            pnlFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFeeLayout.createSequentialGroup()
                .addComponent(btnFeeStruc, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(19, 19, 19)
                .addComponent(btnStudFee))
        );

        btnAtten.setBackground(new java.awt.Color(0, 102, 0));
        btnAtten.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnAtten.setForeground(new java.awt.Color(255, 255, 255));
        btnAtten.setText("Attendance");
        btnAtten.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        btnAtten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttenActionPerformed(evt);
            }
        });

        btnFee.setBackground(new java.awt.Color(0, 102, 0));
        btnFee.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnFee.setForeground(new java.awt.Color(255, 255, 255));
        btnFee.setText("Fee");
        btnFee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        btnFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeeActionPerformed(evt);
            }
        });

        pnlAtten.setBackground(new java.awt.Color(0, 102, 0));

        btnViewA.setBackground(new java.awt.Color(0, 153, 0));
        btnViewA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnViewA.setForeground(new java.awt.Color(255, 255, 255));
        btnViewA.setText("View Attendance");
        btnViewA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAActionPerformed(evt);
            }
        });

        btnMarkA.setBackground(new java.awt.Color(0, 153, 0));
        btnMarkA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnMarkA.setForeground(new java.awt.Color(255, 255, 255));
        btnMarkA.setText("Mark Attendance");
        btnMarkA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAttenLayout = new javax.swing.GroupLayout(pnlAtten);
        pnlAtten.setLayout(pnlAttenLayout);
        pnlAttenLayout.setHorizontalGroup(
            pnlAttenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAttenLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlAttenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMarkA, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAttenLayout.setVerticalGroup(
            pnlAttenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAttenLayout.createSequentialGroup()
                .addComponent(btnMarkA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlEvent.setBackground(new java.awt.Color(0, 102, 0));

        btnUpdateEvent.setBackground(new java.awt.Color(0, 153, 0));
        btnUpdateEvent.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnUpdateEvent.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateEvent.setText("Update Event");
        btnUpdateEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEventActionPerformed(evt);
            }
        });

        btnAddEvent.setBackground(new java.awt.Color(0, 153, 0));
        btnAddEvent.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAddEvent.setForeground(new java.awt.Color(255, 255, 255));
        btnAddEvent.setText("Add Event");
        btnAddEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEventActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEventLayout = new javax.swing.GroupLayout(pnlEvent);
        pnlEvent.setLayout(pnlEventLayout);
        pnlEventLayout.setHorizontalGroup(
            pnlEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEventLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdateEvent, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(btnAddEvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEventLayout.setVerticalGroup(
            pnlEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEventLayout.createSequentialGroup()
                .addComponent(btnAddEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnevent.setBackground(new java.awt.Color(0, 102, 0));
        btnevent.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnevent.setForeground(new java.awt.Color(255, 255, 255));
        btnevent.setText("Event");
        btnevent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        btnevent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneventActionPerformed(evt);
            }
        });

        btnUtility.setBackground(new java.awt.Color(0, 102, 0));
        btnUtility.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnUtility.setForeground(new java.awt.Color(255, 255, 255));
        btnUtility.setText("Utility");
        btnUtility.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        btnUtility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtilityActionPerformed(evt);
            }
        });

        pnlUtility.setBackground(new java.awt.Color(0, 102, 0));

        bnlCalc.setBackground(new java.awt.Color(0, 153, 0));
        bnlCalc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bnlCalc.setForeground(new java.awt.Color(255, 255, 255));
        bnlCalc.setText("Calculator");
        bnlCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnlCalcActionPerformed(evt);
            }
        });

        btnNote.setBackground(new java.awt.Color(0, 153, 0));
        btnNote.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnNote.setForeground(new java.awt.Color(255, 255, 255));
        btnNote.setText("Notepad");
        btnNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoteActionPerformed(evt);
            }
        });

        btnWeb.setBackground(new java.awt.Color(0, 153, 0));
        btnWeb.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnWeb.setForeground(new java.awt.Color(255, 255, 255));
        btnWeb.setText("Web Browser");
        btnWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUtilityLayout = new javax.swing.GroupLayout(pnlUtility);
        pnlUtility.setLayout(pnlUtilityLayout);
        pnlUtilityLayout.setHorizontalGroup(
            pnlUtilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtilityLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlUtilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnWeb, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(bnlCalc, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(btnNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlUtilityLayout.setVerticalGroup(
            pnlUtilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUtilityLayout.createSequentialGroup()
                .addComponent(btnNote, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bnlCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnWeb))
        );

        btnAbout.setBackground(new java.awt.Color(0, 102, 0));
        btnAbout.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(255, 255, 255));
        btnAbout.setText("About Us");
        btnAbout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(0, 102, 0));
        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlStud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAtten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEvent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlUtility, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnExit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDash, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnResult, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAtten, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(btnevent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUtility, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAbout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnl1Layout.createSequentialGroup()
                .addComponent(btnStud, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDash, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStud, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlStud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFee, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtten, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnevent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUtility, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlUtility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        new Result().setVisible(true);
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeeActionPerformed
        // TODO add your handling code here:
        pnlFee.setVisible(val3);
        val3 = !val3;
    }//GEN-LAST:event_btnFeeActionPerformed

    private void btnWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWebActionPerformed
        // TODO add your handling code here:
        try{
            String chromePath = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";
            Runtime.getRuntime().exec(chromePath);
        }catch(IOException e){}
    }//GEN-LAST:event_btnWebActionPerformed

    private void bnlCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnlCalcActionPerformed
        // TODO add your handling code here:
         try{
            Runtime.getRuntime().exec("calc.exe");
        }catch(IOException e){}

    }//GEN-LAST:event_bnlCalcActionPerformed

    private void btnStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudActionPerformed
        // TODO add your handling code here:
        pnlStud.setVisible(val1);
        val1 = !val1;
    }//GEN-LAST:event_btnStudActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        new AddStudent().setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        new UpdateStudent().setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDltActionPerformed
        // TODO add your handling code here:
        new DeleteStudent().setVisible(true);
    }//GEN-LAST:event_btnDltActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        new ViewStudentData().setVisible(true);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
        // TODO add your handling code here:
        pnlResult.setVisible(val2);
        val2 = !val2;
    }//GEN-LAST:event_btnResultActionPerformed

    private void btnAttenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttenActionPerformed
        // TODO add your handling code here:
        pnlAtten.setVisible(val4);
        val4 = !val4;
    }//GEN-LAST:event_btnAttenActionPerformed

    private void btneventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneventActionPerformed
        // TODO add your handling code here:
        pnlEvent.setVisible(val5);
        val5 = !val5;
    }//GEN-LAST:event_btneventActionPerformed

    private void btnUtilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtilityActionPerformed
        // TODO add your handling code here:
        pnlUtility.setVisible(val6);
        val6 = !val6;
    }//GEN-LAST:event_btnUtilityActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnFeeStrucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeeStrucActionPerformed
        // TODO add your handling code here:
        new AttendanceBoard().setVisible(true);
    }//GEN-LAST:event_btnFeeStrucActionPerformed

    private void btnStudFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudFeeActionPerformed
        // TODO add your handling code here:
        new FeeForm().setVisible(true);
    }//GEN-LAST:event_btnStudFeeActionPerformed

    private void btnMarkAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkAActionPerformed
        // TODO add your handling code here:
        new MarkAttendance().setVisible(true);
    }//GEN-LAST:event_btnMarkAActionPerformed

    private void btnViewAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAActionPerformed
        // TODO add your handling code here:
        new AttendanceTrack().setVisible(true);
    }//GEN-LAST:event_btnViewAActionPerformed

    private void btnAddEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEventActionPerformed
        // TODO add your handling code here:
        new AddEvent().setVisible(true);
    }//GEN-LAST:event_btnAddEventActionPerformed

    private void btnUpdateEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEventActionPerformed
        // TODO add your handling code here:
        new EditEvent().setVisible(true);
    }//GEN-LAST:event_btnUpdateEventActionPerformed

    private void btnNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoteActionPerformed
        // TODO add your handling code here:
        try{
            Runtime.getRuntime().exec("notepad.exe");
        }catch(IOException e){}
    }//GEN-LAST:event_btnNoteActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
        new EnterResult().setVisible(true);
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        new AboutUs().setVisible(true);
    }//GEN-LAST:event_btnAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoardMaven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoardMaven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoardMaven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoardMaven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoardMaven().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnlCalc;
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddEvent;
    private javax.swing.JButton btnAtten;
    private javax.swing.JButton btnDash;
    private javax.swing.JButton btnDlt;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFee;
    private javax.swing.JButton btnFeeStruc;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnMarkA;
    private javax.swing.JButton btnNote;
    private javax.swing.JButton btnResult;
    private javax.swing.JButton btnStud;
    private javax.swing.JButton btnStudFee;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateEvent;
    private javax.swing.JButton btnUtility;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnViewA;
    private javax.swing.JButton btnWeb;
    private javax.swing.JButton btnevent;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnlAtten;
    private javax.swing.JPanel pnlEvent;
    private javax.swing.JPanel pnlFee;
    private javax.swing.JPanel pnlResult;
    private javax.swing.JPanel pnlStud;
    private javax.swing.JPanel pnlUtility;
    // End of variables declaration//GEN-END:variables
}
