/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Student;

import java.awt.*;
import java.io.*;
import javax.swing.*;
import javax.swing.filechooser.*;
import java.sql.*;
import student_management.DBConnect1;

/**
 *
 * @author Tanu Panwar
 */
public class UpdateStudent extends javax.swing.JFrame {
    String imgPath,course,branch;
    byte[] oldImage;
    int changeCourse,changeBranch,changeImage;

    /**
     * Creates new form UpdateStudent
     */
    public UpdateStudent() {
        changeCourse=changeBranch=changeImage=0;
        initComponents();
        txtRoll.setEditable(false);// ROLLNO
        txtAadhar.setEditable(false);//AADHAR NO
        ((JTextField)dcDOB.getDateEditor().getUiComponent()).setEditable(false);//DOB
        try{
            Connection con = DBConnect1.connect();
            PreparedStatement ps = con.prepareStatement("select * from studData");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                cmbRollNo.addItem(rs.getString(2));
            }
        }
        catch(Exception e){}
    }
    //Resize the New Pic getting from the user...
    public ImageIcon resizePic(String pic) {
        ImageIcon myimg = new ImageIcon(pic);
        Image img = myimg.getImage().getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_SMOOTH);
        return new ImageIcon(img);
    }
    //Resize the old pic getting from the database...
    public ImageIcon resizePic(byte[] pic){
        ImageIcon myimg =new ImageIcon(pic);
        Image img = myimg.getImage().getScaledInstance(lblImg.getWidth(),lblImg.getHeight(),Image.SCALE_SMOOTH);
        return new ImageIcon(img);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl1 = new javax.swing.JPanel();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblPic = new javax.swing.JLabel();
        lblUpload = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblRoll = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblXII = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtRoll = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtXII = new javax.swing.JTextField();
        cmbCourse = new javax.swing.JComboBox<>();
        lblFather = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblPhn = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        lblBranch = new javax.swing.JLabel();
        txtFather = new javax.swing.JTextField();
        txtPhn = new javax.swing.JTextField();
        txtX = new javax.swing.JTextField();
        cmbBranch = new javax.swing.JComboBox<>();
        lblAadhar = new javax.swing.JLabel();
        txtAadhar = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        cmbRollNo = new javax.swing.JComboBox<>();
        dcDOB = new com.toedter.calendar.JDateChooser();
        lblSetImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl1.setBackground(new java.awt.Color(255, 255, 255));
        pnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmit.setBackground(new java.awt.Color(255, 102, 0));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        pnl1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 120, 40));

        btnCancel.setBackground(new java.awt.Color(255, 102, 0));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pnl1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 590, 120, 40));

        lblPic.setBackground(new java.awt.Color(255, 102, 0));
        lblPic.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPic.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 5), "Update Student", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 24), new java.awt.Color(255, 153, 51))); // NOI18N
        pnl1.add(lblPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1190, 620));

        lblUpload.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblUpload.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpload.setText("Search By Roll No.");
        pnl1.add(lblUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 230, 50));

        lblImg.setBackground(new java.awt.Color(255, 255, 255));
        lblImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 5));
        lblImg.setOpaque(true);
        pnl1.add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 210, 280));

        btnUpload.setBackground(new java.awt.Color(255, 102, 0));
        btnUpload.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        btnUpload.setForeground(new java.awt.Color(255, 255, 255));
        btnUpload.setText("Re-Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        pnl1.add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 180, 50));

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblName.setText("Name");
        pnl1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 150, 40));

        lblRoll.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblRoll.setText("Roll Number");
        pnl1.add(lblRoll, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 130, 40));

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblID.setText("Email ID");
        pnl1.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 196, 130, 40));

        lblXII.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblXII.setText("Class XII (%)");
        pnl1.add(lblXII, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 246, 120, 30));

        lblCourse.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblCourse.setText("Course");
        pnl1.add(lblCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 286, 140, 30));

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        pnl1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 210, 30));

        txtRoll.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtRoll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        pnl1.add(txtRoll, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 152, 210, 30));

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        pnl1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 202, 210, 30));

        txtXII.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtXII.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        pnl1.add(txtXII, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 252, 210, 30));

        cmbCourse.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.Tech", "BCA", "BSC", "M.Tech", "MCA", "MSC" }));
        cmbCourse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        cmbCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCourseActionPerformed(evt);
            }
        });
        pnl1.add(cmbCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 292, 210, 30));

        lblFather.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblFather.setText("Father's Name");
        pnl1.add(lblFather, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 180, 30));

        lblDOB.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblDOB.setText("Date Of Birth");
        pnl1.add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 150, 30));

        lblPhn.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblPhn.setText("Phone");
        pnl1.add(lblPhn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 140, 30));

        lblX.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblX.setText("Class X (%)");
        pnl1.add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 140, 30));

        lblBranch.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblBranch.setText("Branch");
        pnl1.add(lblBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 130, 30));

        txtFather.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtFather.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        pnl1.add(txtFather, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, 180, 30));

        txtPhn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPhn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        pnl1.add(txtPhn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 180, 30));

        txtX.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        pnl1.add(txtX, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 240, 180, 30));

        cmbBranch.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "computer Science", "Mechanical", "Electrical", "Civil", "AI & Technology", " " }));
        cmbBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        cmbBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBranchActionPerformed(evt);
            }
        });
        pnl1.add(cmbBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 290, 180, 30));

        lblAadhar.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblAadhar.setText("Aadhar Number");
        pnl1.add(lblAadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 360, 160, 30));

        txtAadhar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtAadhar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        txtAadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAadharActionPerformed(evt);
            }
        });
        pnl1.add(txtAadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 640, 30));

        lblAddress.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblAddress.setText("Address");
        pnl1.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 140, 50));

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtArea.setRows(5);
        txtArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jScrollPane1.setViewportView(txtArea);

        pnl1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 416, 640, 120));

        cmbRollNo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbRollNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbRollNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        cmbRollNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRollNoActionPerformed(evt);
            }
        });
        pnl1.add(cmbRollNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 112, 200, 40));

        dcDOB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        dcDOB.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pnl1.add(dcDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 144, 180, 30));

        lblSetImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NewStud.jpg"))); // NOI18N
        pnl1.add(lblSetImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 630));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, 1208, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        changeImage = 1;
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filefilter = new FileNameExtensionFilter(".Images", "jpg", "png", "jpeg", "gif");

        file.addChoosableFileFilter(filefilter);
        int filestate = file.showSaveDialog(null);

        if (filestate == JFileChooser.APPROVE_OPTION) {
            File sf = file.getSelectedFile();
            String path = sf.getAbsolutePath();

            lblImg.setIcon(resizePic(path));
            imgPath = path;
        }
        else if (filestate == JFileChooser.CANCEL_OPTION) {
            JOptionPane.showConfirmDialog(null, "NO IMAGE SELECTED");
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void txtAadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAadharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAadharActionPerformed

    private void cmbRollNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRollNoActionPerformed
        // TODO add your handling code here:
         try{
            Connection con = DBConnect1.connect();
            PreparedStatement ps = con.prepareStatement("select * from studData where rollno=?");
            ps.setString(1,cmbRollNo.getSelectedItem().toString()); 

            ResultSet rs = ps.executeQuery();
            while(rs.next()){
               txtName.setText(rs.getString(1));// name
               txtRoll.setText(rs.getString(2));// rollno
               txtID.setText(rs.getString(3));// email
               txtXII.setText(rs.getString(4));// xii
                // course
               course = rs.getString(5);
               txtAadhar.setText(rs.getString(6));// aadhar
               txtArea.setText(rs.getString(7));// address
               txtFather.setText(rs.getString(8));// fname
               ((JTextField)dcDOB.getDateEditor().getUiComponent()).setText(rs.getString(9));// dob
               txtPhn.setText(rs.getString(10));// phone
               txtX.setText(rs.getString(11));// x
                // branch
               branch = rs.getString(12);
                // image
                oldImage =rs.getBytes(13);
                lblImg.setIcon(resizePic(oldImage));
           }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_cmbRollNoActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(changeCourse==1){
            course = cmbCourse.getSelectedItem().toString();
        }
        if(changeBranch==1){
            branch = cmbBranch.getSelectedItem().toString();
        }
        try{
            Connection con = DBConnect1.connect();
            PreparedStatement ps = con.prepareStatement("update studData set name=?,rollno=?,"+
                    "email=?,xii=?,course=?,AadharNo=?,"+
                    "address=?,fname=?,dob=?,phone=?,x=?,branch=?,image=? where rollno=?");
            ps.setString(1,txtName.getText()); // name
            ps.setString(2,txtRoll.getText()); // roll no
            ps.setString(3,txtID.getText()); // email id
            ps.setString(4,txtXII.getText()); // class xii
            ps.setString(5,course); // course
            ps.setString(6,txtAadhar.getText()); // aadhar
            ps.setString(7,txtArea.getText()); // address
            ps.setString(8,txtFather.getText()); // father
            ps.setString(9,((JTextField)dcDOB.getDateEditor().getUiComponent()).getText()); // dob
            ps.setString(10,txtPhn.getText()); // phone
            ps.setString(11,txtX.getText()); // x class
            ps.setString(12,branch); // branch
            if(changeImage==1){
                InputStream ig = new FileInputStream(new File(imgPath));
                ps.setBlob(13,ig);
            }
            else{
                ps.setBlob(13,new ByteArrayInputStream(oldImage));
            }
            ps.setString(14,txtRoll.getText());
            int a = ps.executeUpdate();
            if(a==1){
                JOptionPane.showMessageDialog(null,"Successfully registered a new Student");
                dispose();
            }
            else
            JOptionPane.showMessageDialog(null,"Some Error");

        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void cmbCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCourseActionPerformed
        // TODO add your handling code here:
        changeCourse = 1;
    }//GEN-LAST:event_cmbCourseActionPerformed

    private void cmbBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBranchActionPerformed
        // TODO add your handling code here:
        changeBranch = 1;
    }//GEN-LAST:event_cmbBranchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UpdateStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpload;
    private javax.swing.JComboBox<String> cmbBranch;
    private javax.swing.JComboBox<String> cmbCourse;
    private javax.swing.JComboBox<String> cmbRollNo;
    private com.toedter.calendar.JDateChooser dcDOB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAadhar;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblFather;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhn;
    private javax.swing.JLabel lblPic;
    private javax.swing.JLabel lblRoll;
    private javax.swing.JLabel lblSetImg;
    private javax.swing.JLabel lblUpload;
    private javax.swing.JLabel lblX;
    private javax.swing.JLabel lblXII;
    private javax.swing.JPanel pnl1;
    private javax.swing.JTextField txtAadhar;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtFather;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhn;
    private javax.swing.JTextField txtRoll;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtXII;
    // End of variables declaration//GEN-END:variables
}
