/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Fee;
import java.sql.Connection;
import java.sql.*;
import javax.swing.JOptionPane;
import student_management.DBConnect1;

/**
 *
 * @author Tanu Panwar
 */
public class StudFeeForm extends javax.swing.JFrame {
    String totalAmt;
    String rollno;
    int changePendFee = 0;
    int flag = 0;

    /**
     * Creates new form StudFeeForm
     */
    public StudFeeForm() {
        initComponents();
        try{
            Connection con = DBConnect1.connect();
            PreparedStatement ps = con.prepareStatement("Select * from studData");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                cmbRollNo.addItem(rs.getString("RollNo"));
            }
        }catch(SQLException e){
            System.out.println(e);
        }
    }
    
    public void fetchStud(){
        cmbRollNo.removeAllItems();
        try{
            Connection con = DBConnect1.connect();
            // To Fetch all the roll numbers...
            PreparedStatement ps = con.prepareStatement("Select * from studData",ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            ResultSet rs = ps.executeQuery();
            
            // To Fetch all the students who had submitted thier full fee...
            PreparedStatement ps1 = con.prepareStatement("select * from studFee where status = 'Done' and year = ?" ,ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            ps1.setString(1, cmbYear.getSelectedItem().toString());
            ResultSet rs1 = ps1.executeQuery();
            
            // In this nested looping we will eliminate all those roll no who have completely submitted their fee...
            /* 
            eg:            roll no from studData are 1,2,3,4,5
            eg :          roll no -- 1  status -> done
            eg :          roll no -- 2  status -> pending
            eg :          roll no -- 3  status -> pending
            eg :          roll no -- 4  status -> done
            there records came from studFee now adding only 2,3,5 to the comboBox as only their fee is pending...
            */
            
            while(rs.next()){
                String studentRollNo = rs.getString("RollNo");
                
                // BeforeFirst() is used to reset the cursor to the next
                rs1.beforeFirst();
                while(rs1.next()){
                    if(rs1.getString("RollNo").equalsIgnoreCase(studentRollNo)){
                        flag = 1;
                        break;
                    }else{
                        flag = 0;
                    }
                }
                if(flag == 0){
                    cmbRollNo.addItem(rs.getString("RollNo"));
                }
            }          
        }catch(SQLException e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFee = new javax.swing.JPanel();
        lblFee = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblRooNo = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        lblBranch = new javax.swing.JLabel();
        lblAmt = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCourse = new javax.swing.JTextField();
        txtBranch = new javax.swing.JTextField();
        txtAmt = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cmbYear = new javax.swing.JComboBox<>();
        cmbRollNo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFee.setBackground(new java.awt.Color(255, 255, 255));
        pnlFee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0), 5));

        lblFee.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblFee.setForeground(new java.awt.Color(0, 51, 0));
        lblFee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFee.setText("Student Fee Form");

        lblYear.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        lblYear.setForeground(new java.awt.Color(0, 51, 0));
        lblYear.setText("Year");

        lblRooNo.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        lblRooNo.setForeground(new java.awt.Color(0, 51, 0));
        lblRooNo.setText("Roll No");

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 51, 0));
        lblName.setText("Name");

        lblCourse.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        lblCourse.setForeground(new java.awt.Color(0, 51, 0));
        lblCourse.setText("Course");

        lblBranch.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        lblBranch.setForeground(new java.awt.Color(0, 51, 0));
        lblBranch.setText("Branch");

        lblAmt.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        lblAmt.setForeground(new java.awt.Color(0, 51, 0));
        lblAmt.setText("Amount");

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0), 2));

        txtCourse.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        txtCourse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0), 2));

        txtBranch.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        txtBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0), 2));

        txtAmt.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        txtAmt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0), 2));
        txtAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmtActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(0, 51, 0));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(0, 51, 0));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        cmbYear.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cmbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "first", "second", "third", "fourth" }));
        cmbYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0), 2));
        cmbYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbYearActionPerformed(evt);
            }
        });

        cmbRollNo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cmbRollNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0), 2));
        cmbRollNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRollNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFeeLayout = new javax.swing.GroupLayout(pnlFee);
        pnlFee.setLayout(pnlFeeLayout);
        pnlFeeLayout.setHorizontalGroup(
            pnlFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFeeLayout.createSequentialGroup()
                .addGroup(pnlFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFeeLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlFeeLayout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlFeeLayout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addGroup(pnlFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlFeeLayout.createSequentialGroup()
                                    .addComponent(lblAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(43, 43, 43)
                                    .addComponent(txtAmt))
                                .addGroup(pnlFeeLayout.createSequentialGroup()
                                    .addComponent(lblBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(43, 43, 43)
                                    .addComponent(txtBranch))
                                .addGroup(pnlFeeLayout.createSequentialGroup()
                                    .addComponent(lblCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(43, 43, 43)
                                    .addComponent(txtCourse))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFeeLayout.createSequentialGroup()
                                    .addGroup(pnlFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                        .addComponent(lblRooNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(35, 35, 35)
                                    .addGroup(pnlFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtName)
                                        .addComponent(cmbRollNo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFeeLayout.createSequentialGroup()
                .addComponent(lblFee, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlFeeLayout.setVerticalGroup(
            pnlFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFee, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(pnlFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnlFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRooNo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(cmbRollNo))
                .addGap(20, 20, 20)
                .addGroup(pnlFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFeeLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFeeLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFeeLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFeeLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(pnlFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = DBConnect1.connect();
            PreparedStatement ps = con.prepareStatement("select * from feeStruct where course = ? and branch = ?");
            ps.setString(1,txtCourse.getText());
            ps.setString(2, txtBranch.getText());
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                totalAmt = rs.getString(cmbYear.getSelectedItem().toString());
            }
            int subAmt = Integer.parseInt(txtAmt.getText());
            int pend = Integer.parseInt(totalAmt)-subAmt;
            
            if(changePendFee == 1){
                PreparedStatement ps1 = con.prepareStatement("Insert into studFee values(?,?,?,?)");
                 ps1.setString(1,rollno);
                ps1.setString(2,String.valueOf(pend));
                ps1.setString(4,cmbYear.getSelectedItem().toString());
                
                if(subAmt > Integer.parseInt(totalAmt)){
                 JOptionPane.showMessageDialog(null,(-pend)+" Full fee submitted successfully and extra amount returned");
                        ps1.setString(3,"Done");
            }else{
                if(pend!=0){
                        JOptionPane.showMessageDialog(null,pend+" Amount to be submitted");
                        ps1.setString(3,"Pending");
                }else{
                        JOptionPane.showMessageDialog(null," Full fee submitted successfully");
                        ps1.setString(3,"Done");
                }
            }
               System.out.println(ps1);
                ps1.executeUpdate();
            }else{
                //Fetch data from studFee for fee of student....
                PreparedStatement ps2 = con.prepareStatement("update studfee set fee = ? and  status = ? where rollno=? ");
                ps2.setString(1,String.valueOf(pend));
                ps2.setString(3,rollno);              
              //  if(pend!=0){
                    if(subAmt > Integer.parseInt(totalAmt)){
                 JOptionPane.showMessageDialog(null,(-pend)+"full fee submitted successfully and extra amount returned");
                        ps2.setString(2,"done");
            }else{
                        if(pend !=0){
                        JOptionPane.showMessageDialog(null,pend+" amount to be submitted");
                        ps2.setString(2,"pending");
                }else{
                        JOptionPane.showMessageDialog(null,"full fee submitted successfully");
                        ps2.setString(2,"done");
                }
                }
                System.out.println(ps2);
                ps2.executeUpdate();
            }  
        }catch(Exception e){
        System.out.println(e);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmtActionPerformed
 
    }//GEN-LAST:event_txtAmtActionPerformed

    private void cmbRollNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRollNoActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtCourse.setText("");
        txtBranch.setText("");
        txtAmt.setText("");
        try{
            if(cmbRollNo.getSelectedItem() != null){
            rollno = cmbRollNo.getSelectedItem().toString();
            Connection con = DBConnect1.connect();
            
            // To fetch details of students...
            PreparedStatement ps = con.prepareStatement("select * from studData where rollno=?");
            ps.setString(1,rollno);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                txtName.setText(rs.getString(1));
                txtCourse.setText(rs.getString(5));
                txtBranch.setText(rs.getString(12));
            }
            
            // To pending fee of student
            PreparedStatement ps2 = con.prepareStatement("select * from studfee where rollno=? and year=?");
            ps2.setString(1,rollno);
            ps2.setString(2,cmbYear.getSelectedItem().toString());
            ResultSet rs2 = ps2.executeQuery();
            while(rs2.next()){
                txtAmt.setText(rs2.getString("fee"));
            }
//            System.out.println("t6.getText()");
//            System.out.println(t6.getText());
             if(txtAmt.getText().equalsIgnoreCase("")){
                 changePendFee =1;
            }else{
                 changePendFee =0;
             }
           }
        }catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_cmbRollNoActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cmbYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbYearActionPerformed
        // TODO add your handling code here:
        fetchStud();
    }//GEN-LAST:event_cmbYearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudFeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudFeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudFeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudFeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new StudFeeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbRollNo;
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JLabel lblAmt;
    private javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblFee;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRooNo;
    private javax.swing.JLabel lblYear;
    private javax.swing.JPanel pnlFee;
    private javax.swing.JTextField txtAmt;
    private javax.swing.JTextField txtBranch;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
