/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Attendance;

import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import student_management.DBConnect1;
import java.util.Date;
/**
 *
 * @author Tanu Panwar
 */
public class AttendanceTrack extends javax.swing.JFrame {
     int pr=0,ab=0;
     String date1,date2,defaultDate;
    public AttendanceTrack (){
        initComponents();
        Date today = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
         String fd = sdf.format(today);
        defaultDate=fd;
//        System.out.print(defaultDate);
        int sno =1;
         try{
            Connection con = DBConnect1.connect();
            PreparedStatement ps = con.prepareStatement("select s1.rollno, s1.name, a1.pa  from studData s1 join attendence a1 on s1.rollno = a1.rollno ");
            ResultSet rs = ps.executeQuery();
             while(rs.next()){
                String rollno = rs.getString("rollno");
                String name = rs.getString("name");
                String present = rs.getString("pa");
                String absent ="";
                if(present.equalsIgnoreCase("-")){
                    ab++;  absent = "-"; }
                if(present.equalsIgnoreCase("absent")){
                    ab++; absent = "absent";}
                else{ pr++;  }
                String sno1 = String.valueOf(sno);
                String tbData[] ={sno1,rollno,name,present,absent};
                DefaultTableModel tb1Model=(DefaultTableModel)tblTrack.getModel();
                tb1Model.addRow(tbData);
                sno++;
  }
//            for those who have two label
            lblPre.setText(String.valueOf(pr));
            lblAb.setText(String.valueOf(ab));
//          for those who only have one label
//                p.setText("Present "+String.valueOf(pr));
//                a.setText("Absent "+String.valueOf(ab));
             pr=ab=0;
            }catch(Exception e){
             System.out.println(e);
         }
    }
     public void clearTable(JTable table) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
    }
   



    /**
     * Creates new form AttendanceTrack
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTrack = new javax.swing.JLabel();
        lblFrom = new javax.swing.JLabel();
        dateFrom = new com.toedter.calendar.JDateChooser();
        lblTo = new javax.swing.JLabel();
        dateTo = new com.toedter.calendar.JDateChooser();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTrack = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnGo = new javax.swing.JButton();
        lblPresent = new javax.swing.JLabel();
        lblAbsent = new javax.swing.JLabel();
        lblPre = new javax.swing.JLabel();
        lblAb = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204), 5));

        lblTrack.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTrack.setForeground(new java.awt.Color(153, 0, 255));
        lblTrack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrack.setText("Attendance Track");

        lblFrom.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        lblFrom.setForeground(new java.awt.Color(153, 0, 255));
        lblFrom.setText("From :");

        dateFrom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255)));
        dateFrom.setDateFormatString("dd/MM/yyyy");
        dateFrom.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lblTo.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        lblTo.setForeground(new java.awt.Color(153, 0, 255));
        lblTo.setText("To :");

        dateTo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255)));
        dateTo.setDateFormatString("dd/MM/yyyy");
        dateTo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btnSearch.setBackground(new java.awt.Color(153, 0, 255));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblTrack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255), 2));
        tblTrack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblTrack.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sno.", "Roll Number", "Name", "Present", "Absent"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTrack);

        btnBack.setBackground(new java.awt.Color(153, 0, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblSearch.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(153, 0, 255));
        lblSearch.setText("Search :");

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255)));

        btnGo.setBackground(new java.awt.Color(153, 0, 255));
        btnGo.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        btnGo.setForeground(new java.awt.Color(255, 255, 255));
        btnGo.setText("Go");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        lblPresent.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        lblPresent.setForeground(new java.awt.Color(51, 255, 0));
        lblPresent.setText("Present");

        lblAbsent.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        lblAbsent.setForeground(new java.awt.Color(255, 0, 0));
        lblAbsent.setText("Absent");

        lblPre.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        lblPre.setForeground(new java.awt.Color(51, 255, 0));
        lblPre.setText("----------");

        lblAb.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        lblAb.setForeground(new java.awt.Color(255, 0, 0));
        lblAb.setText("----------");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblAbsent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPresent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addGap(0, 866, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 917, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(92, 92, 92)
                                    .addComponent(lblFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(163, 163, 163)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblPre, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(lblAb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(202, 202, 202)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblSearch)
                                    .addGap(12, 12, 12)
                                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(7, 7, 7)
                                    .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblTo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(396, 396, 396)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblTrack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTrack, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTo))
                        .addGap(13, 13, 13)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPresent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
          try{
           clearTable(tblTrack);
           SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            date1 = (dateFrom.getDate() != null) ? sdf.format(dateFrom.getDate()) : defaultDate;
            date2 = (dateTo.getDate() != null) ? sdf.format(dateTo.getDate()) : defaultDate;
              int sno =1;
              Connection con = DBConnect1.connect();
              PreparedStatement ps = con.prepareStatement("select  *  from studata s1 join attendence a1 on s1.rollno = a1.rollno where a1.date between ? and ?");
            ps.setString(1,date1);
            ps.setString(2,date2);
            ResultSet rs = ps.executeQuery();
             int count =0;
            while(rs.next()){
                     count++;
//                System.out.println(rs.getString("rollno"));
                String rollno = rs.getString("rollno");
                String name = rs.getString("name");
                String present = rs.getString("pa");
                String absent ="";
                if(present.equalsIgnoreCase("-")){
                    ab++;
                    absent = "-";
                }
                if(present.equalsIgnoreCase("absent")){
                    ab++;
                    absent = "absent";
                }
                else{
                    pr++;
                }
//                System.out.println(count);
                String sno1 = String.valueOf(sno);
                String tbData[] ={sno1,rollno,name,present,absent};
                DefaultTableModel tb1Model=(DefaultTableModel)tblTrack.getModel();
                tb1Model.addRow(tbData);
                sno++;
            }
            lblPre.setText(String.valueOf(pr));
            lblAb.setText(String.valueOf(ab));
            pr=ab=0;

       }catch(Exception e){
           System.out.print(e);
                   
       }

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        // TODO add your handling code here:
          clearTable(tblTrack);
        int sno =1;
        try{
            Connection con = DBConnect1.connect();
            PreparedStatement ps = con.prepareStatement(
                    "select s1.rollno, s1.name, a1.pa  from studata s1 " +
                            "join attendence a1 on s1.rollno = a1.rollno where a1.rollno=? "
            );
            ps.setString(1,txtSearch.getText());
            ResultSet rs = ps.executeQuery();
                            
             int count =0;
            while(rs.next()){
                count++;
//                System.out.println(rs.getString("rollno"));
                String rollno = rs.getString("rollno");
                String name = rs.getString("name");
                String present = rs.getString("pa");
 String absent ="";
                if(!present.equalsIgnoreCase("present")){
                    ab++;
                    absent = "absent";
                }
                else{
                    pr++;
                }
//                System.out.println(count);
                String sno1 = String.valueOf(sno);
                String tbData[] ={sno1,rollno,name,present,absent};
                DefaultTableModel tb1Model=(DefaultTableModel)tblTrack.getModel();
                tb1Model.addRow(tbData);
                sno++;
            }
   if(count==0){
               JOptionPane.showMessageDialog(null,"No such roll number found");
           }  
            lblPre.setText(String.valueOf(pr));
            lblAb.setText(String.valueOf(ab));
            pr=ab=0;
        }catch(Exception e){}

    }//GEN-LAST:event_btnGoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendanceTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendanceTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendanceTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendanceTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttendanceTrack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnSearch;
    private com.toedter.calendar.JDateChooser dateFrom;
    private com.toedter.calendar.JDateChooser dateTo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAb;
    private javax.swing.JLabel lblAbsent;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblPre;
    private javax.swing.JLabel lblPresent;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTo;
    private javax.swing.JLabel lblTrack;
    private javax.swing.JTable tblTrack;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
